### FOR LOCAL DEVELOPMENT ONLY ###
### see infrastructure repo for staging and production ready deployment ###

version: '3.9'
services:
  survey:
    restart: unless-stopped
    build: src/
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on: [ postgres ]

  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
