name: Publish Docker Image
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@v2
        with:
          repository: 'JonasCir/open-survey-infra'
          path: infra
