name: Publish Docker
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, development ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@v2
        with:
          repository: 'JonasCir/open-survey-infra'
          path: infra
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: repo

        # production grade deployments need special setup (WSGI, static files served via nginx, etc.)
      - run: cp infra/docker/staging/setup_and_run.sh repo/src/config

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.9.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: jonascir/open-survey-tool
          tag_with_ref: true
          path: repo/src/

  deploy:
    # https://github.com/marketplace/actions/docker-deployment:
    name: Deploy to staging
    runs-on: ubuntu-20.04
    needs: [ push_to_registry ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

